"""
Tracks what's left to do now that bots look at the screen instead of asking the (disabled) RuneLite plugin APIs.
Scans every OSRS bot and writes `VISION_TODO.md` at the root of the repository, listing per bot:
    - the item sprites it needs in `src/images/bot/items/`, and whether each one exists yet
    - `TODO(vision)` comments left in its code
    - calls it still makes that have no vision-based equivalent

Run from the `src` folder:
    python -m utilities.vision_todo            Rewrite the checklist.
    python -m utilities.vision_todo --fetch    Also try downloading the missing sprites from the OSRS Wiki first.
"""
import json
import re
import sys
from pathlib import Path
from typing import Dict, List, NamedTuple, Tuple, Union
from urllib.parse import quote

import utilities.api.item_ids as item_ids
from utilities.api.vision_api import ITEM_SPRITES, MISSING_SPRITES_LOG, UNSUPPORTED_CALLS, sprite_filenames

SRC = Path(__file__).parent.parent
BOTS_FOLDER = SRC.joinpath("model", "osrs")
CHECKLIST = SRC.parent.joinpath("VISION_TODO.md")

__ITEM_REFERENCE = re.compile(r"\b(?:ids|item_ids)\.([A-Za-z_][A-Za-z_0-9]*)")
__TODO_MARKER = re.compile(r"#\s*TODO\(vision\):\s*(.*)")
__API_CALL = re.compile(r"\.(\w+)\(")


class BotReport(NamedTuple):
    name: str
    sprites: List[Tuple[str, int, bool]]  # (filename, item ID, whether the sprite exists)
    todos: List[Tuple[int, str]]  # (line number, text)
    unsupported_calls: List[Tuple[int, str]]  # (line number, function name)
    broken: bool = False  # True if the bot isn't valid Python, in which case it wasn't scanned


def scan_bot(name: str, source: str, sprite_dir: Path = ITEM_SPRITES) -> BotReport:
    """
    Works out what a bot still needs by reading its source code.
    Args:
        name: What to call the bot in the report.
        source: The bot's source code.
        sprite_dir: Folder containing the item sprites.
    """
    try:
        compile(source, name, "exec")
    except SyntaxError:
        return BotReport(name, [], [], [], broken=True)
    sprites, todos, unsupported_calls = {}, [], []
    for line_number, line in enumerate(source.splitlines(), start=1):
        if todo := __TODO_MARKER.search(line):
            todos.append((line_number, todo[1].strip()))
        if line.strip().startswith("#"):
            continue
        for constant in __ITEM_REFERENCE.findall(line):
            value = getattr(item_ids, constant, None)
            for item_id in value if isinstance(value, list) else [value]:
                if filenames := sprite_filenames(item_id) if isinstance(item_id, int) else []:
                    sprites[item_id] = (filenames[0], item_id, any(sprite_dir.joinpath(f).exists() for f in filenames))
        unsupported_calls += [(line_number, call) for call in __API_CALL.findall(line) if call in UNSUPPORTED_CALLS]
    return BotReport(name, sorted(sprites.values()), todos, unsupported_calls)


def render_markdown(reports: List[BotReport], runtime_missing: Dict[str, dict]) -> str:
    """
    Renders the checklist.
    Args:
        reports: The scanned bots.
        runtime_missing: The contents of `vision_missing_sprites.json` (sprites that bots asked for while running).
    """
    lines = [
        "# Vision TODO",
        "",
        "Generated by `python -m utilities.vision_todo` (run from `src`). Don't edit by hand; rerun it after adding sprites.",
        "",
        "Sprites go in `src/images/bot/items/`, named as listed. Until a sprite exists, bots treat that item as *not found*.",
        "",
    ]
    if runtime_missing:
        lines += ["## Asked for while a bot was running", ""]
        for filename, entry in sorted(runtime_missing.items()):
            lines.append(f"- [ ] `{filename}` (item {entry['item_id']}) needed by {', '.join(entry['requested_by'])}")
        lines.append("")
    for report in reports:
        if report.broken:
            lines += [f"## {report.name} (skipped: doesn't parse as Python)", ""]
            continue
        if not (report.sprites or report.todos or report.unsupported_calls):
            continue
        have = sum(exists for _, _, exists in report.sprites)
        lines += [f"## {report.name} ({have}/{len(report.sprites)} sprites)", ""]
        lines += [f"- [{'x' if exists else ' '}] `{filename}` (item {item_id})" for filename, item_id, exists in report.sprites]
        if report.todos:
            lines += ["", "Code marked `TODO(vision)`:", ""]
            lines += [f"- [ ] line {line_number}: {text}" for line_number, text in report.todos]
        if report.unsupported_calls:
            lines += ["", "Calls with no vision-based equivalent (they return an \"unknown\" value):", ""]
            lines += [f"- [ ] line {line_number}: `{call}()`" for line_number, call in report.unsupported_calls]
        lines.append("")
    return "\n".join(lines)


def scan_all_bots() -> List[BotReport]:
    paths = sorted(path for path in BOTS_FOLDER.rglob("*.py") if path.name != "__init__.py")
    return [scan_bot(str(path.relative_to(SRC).as_posix()), path.read_text(encoding="utf-8")) for path in paths]


# Sprites whose name in item_ids.py can't be turned into the OSRS Wiki's name for them: {our filename: Wiki file}.
# The IDs of the three pre-2019 nests (5073, 7413, 13653) are a best guess; every other entry is from the Wiki's infobox.
WIKI_FILE_OVERRIDES = {
    "Barbtail_harpoon.png": "Barb-tail harpoon.png",
    "Bird_nest.png": "Bird nest (red egg).png",
    "Bird_nest_5071.png": "Bird nest (green egg).png",
    "Bird_nest_5072.png": "Bird nest (blue egg).png",
    "Bird_nest_5073.png": "Bird nest (seeds, 2005-2019).png",
    "Bird_nest_5074.png": "Bird nest (ring).png",
    "Bird_nest_5075.png": "Bird nest (empty).png",
    "Bird_nest_7413.png": "Bird nest (Wyson, 2006-2016).png",
    "Bird_nest_13653.png": "Bird nest (Wyson, 2016-2019).png",
    "Bird_nest_22798.png": "Bird nest (seeds).png",
    "Bird_nest_22800.png": "Bird nest (Wyson).png",
    "Clue_bottle_beginner.png": "Clue bottle (beginner).png",
    "Clue_bottle_easy.png": "Clue bottle (easy).png",
    "Clue_bottle_medium.png": "Clue bottle (medium).png",
    "Clue_bottle_hard.png": "Clue bottle (hard).png",
    "Clue_bottle_elite.png": "Clue bottle (elite).png",
    "Dragon_pickaxe_or.png": "Dragon pickaxe (or).png",
    "Dragon_pickaxe_or_25376.png": "Dragon pickaxe (or) (Trailblazer).png",
    "Paydirt.png": "Pay-dirt.png",
    "Slice_of_cake.png": "Slice of cake.png",
    "Tangled_toads_legs.png": "Tangled toad's legs.png",
    "_23_cake.png": "2-3 cake.png",
}


def wiki_override_url(sprite_filename: str) -> Union[str, None]:
    """
    Returns where to download a sprite from if the OSRS Wiki calls it something else, or None if it doesn't.
    """
    if wiki_file := WIKI_FILE_OVERRIDES.get(sprite_filename):
        return f"https://oldschool.runescape.wiki/images/{quote(wiki_file.replace(' ', '_'))}"
    return None


def fetch_missing_sprites(reports: List[BotReport]) -> None:
    """
    Tries to download each missing sprite from the OSRS Wiki. Names that don't match a Wiki page stay on the checklist.
    """
    import requests

    from utilities.sprite_scraper import SpriteScraper

    missing = sorted({filename for report in reports for filename, _, exists in report.sprites if not exists})
    for filename in [f for f in missing if wiki_override_url(f)]:
        response = requests.get(wiki_override_url(filename), headers={"User-Agent": "OSBC sprite fetcher"}, timeout=20)
        if response.ok and response.content.startswith(b"\x89PNG"):
            ITEM_SPRITES.joinpath(filename).write_bytes(response.content)
            print(f"Success: {filename} saved from {WIKI_FILE_OVERRIDES[filename]}")
        else:
            print(f"Couldn't download {WIKI_FILE_OVERRIDES[filename]} for {filename} (HTTP {response.status_code}).")
    search_terms = [re.sub(r"_\d+$", "", Path(f).stem).replace("_", " ") for f in missing if not wiki_override_url(f)]
    if search_terms:
        SpriteScraper().search_and_download(", ".join(dict.fromkeys(search_terms)), destination=ITEM_SPRITES)


def main() -> None:
    if "--fetch" in sys.argv:
        fetch_missing_sprites(scan_all_bots())
    reports = scan_all_bots()
    try:
        runtime_missing = json.loads(MISSING_SPRITES_LOG.read_text())
    except (FileNotFoundError, json.JSONDecodeError):
        runtime_missing = {}
    # Sprites that have been added since they were reported don't need chasing anymore.
    runtime_missing = {filename: entry for filename, entry in runtime_missing.items() if not ITEM_SPRITES.joinpath(filename).exists()}
    CHECKLIST.write_text(render_markdown(reports, runtime_missing), encoding="utf-8")
    sprites = {sprite for report in reports for sprite in report.sprites}
    print(f"{sum(exists for _, _, exists in sprites)}/{len(sprites)} sprites present. Checklist written to {CHECKLIST}")


if __name__ == "__main__":
    main()
